#require "test-form.rb"require 'watir'
require 'webdrivers'
require 'faker'
require 'roo'
require 'rubygems'
require 'f:\courses\2021-2022 I\Software Testing and Quality Assurance\Watir\btl\Test1.rb'
require 'f:\courses\2021-2022 I\Software Testing and Quality Assurance\Watir\btl\Test2.rb'
require 'f:\courses\2021-2022 I\Software Testing and Quality Assurance\Watir\btl\Test3.rb'
require 'f:\courses\2021-2022 I\Software Testing and Quality Assurance\Watir\btl\Test4.rb'
require 'f:\courses\2021-2022 I\Software Testing and Quality Assurance\Watir\btl\Test5.rb'
require 'f:\courses\2021-2022 I\Software Testing and Quality Assurance\Watir\btl\Test6.rb'
require 'f:\courses\2021-2022 I\Software Testing and Quality Assurance\Watir\btl\Test7.rb'
require 'f:\courses\2021-2022 I\Software Testing and Quality Assurance\Watir\btl\Test8.rb'